name: build

on:
    workflow_call:
jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                include:
                    # Windows 32-bit
                    - os: windows-latest
                      arch: Win32
                      name: win32

                    # Windows 64-bit
                    - os: windows-latest
                      arch: x64
                      name: win64

        runs-on: ${{ matrix.os }}
        name: Build (${{ matrix.name }})
        steps:
            - uses: actions/checkout@v3

            - name: Build (Windows)
              if: runner.os == 'Windows'
              run: |
                  cmake -B build -A ${{ matrix.arch }}
                  cmake --build build --config Release

            - name: Archive artifacts (Windows)
              if: runner.os == 'Windows'
              run: Compress-Archive -Path build/Release/* -DestinationPath build/release-${{ matrix.name }}.zip

            - name: Upload artifacts (Windows)
              if: runner.os == 'Windows'
              uses: actions/upload-artifact@v4
              with:
                name: build-${{ matrix.name }}
                path: build/release-${{ matrix.name }}.zip