name: CI

on:
    push:
        branches: 
            - main
            - develop
            - feature/CoreCmake
    pull_request:
        branches:
            - '!main'
            - '!develop'
jobs:
    format:
        uses: ./.github/workflows/format.yml
    build:
        needs: format
        uses: ./.github/workflows/build.yml
    test:
        needs: build
        uses: ./.github/workflows/test.yml