name: clang-format

on:
    workflow_call:

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install clang-format
              run: sudo apt-get install -y clang-format

            - name: Format code
              run: |
                find . \( -name "*.cpp" -o -name "*.hpp" \) | \
                xargs clang-format -i

            - name: Check for changes
              run: |
                git diff --exit-code || (echo "Code is not formatted. Run clang-format locally." && exit 1)