name: test

on:
    workflow_call:

jobs:
    unit_tests:
        strategy:
            matrix:
                include:
                    # Windows 32-bit
                    - os: windows-latest
                      arch: Win32
                      name: win32

                    # Windows 64-bit
                    - os: windows-latest
                      arch: x64
                      name: win64

                    # Ubuntu 16.04 x64 
                    - os: ubuntu-latest
                      container: ubuntu:16.04
                      name: ubuntu-1604

                    # Ubuntu 18.04 x64 
                    - os: ubuntu-latest
                      container: ubuntu:18.04
                      name: ubuntu-1804

        runs-on: ${{ matrix.os }}
        name: Unit Tests (${{ matrix.name }})
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                name: build-${{ matrix.name }}
                path: build

            - name: Run unit tests (Windows)
              if: runner.os == 'Windows'
              run: |
                cd build
                ctest --output-on-failure -C Release

            - name: Run unit tests (Linux)
              if: runner.os == 'Linux'
              run: |
                  docker run --rm \
                    -v ${{ github.workspace }}/build:/build \
                    -w /build \
                    ${{ matrix.container }} \
                    bash -c "ctest --output-on-failure"